etertimemachine: add initial --link support, improve help

diff --git a/bin/etertimemachine b/bin/etertimemachine
--- a/bin/etertimemachine
+++ b/bin/etertimemachine
@@ -18,7 +18,7 @@
 
 export LANG=C
 
-DESCR="etertimemachine version 0.2 (c) Etersoft 2015"
+DESCR="etertimemachine version 0.3 (c) Etersoft 2015"
 
 # last
 # -1, -2, -3
@@ -183,6 +183,15 @@ update_dir()
 	# if rotate_dir will fail, we will exit via fatal
 	[ -z "$STATUS" ] && rotate_dir
 
+	if [ -n "$MAKELINK" ] ; then
+		set_status "sync"
+		echo "Hardlinking for first time... TODO: what do for next time?"
+		cp -a -l "$BACKUPDIR/" "$ROTATEDIR/$LAST/" || fatal "Can't copy. Try again this command."
+		set_status ""
+		echo "Done."
+		return
+	fi
+
 	set_status "sync"
 	if [ -d "$ROTATEDIR/$LAST" ] ; then
 		echo "Syncing $BACKUPDIR to $ROTATEDIR/$LAST..."
@@ -214,10 +223,10 @@ if [ "$1" = "--force" ] ; then
 	FORCE=1
 fi
 
-DEBUG=
-if [ "$1" = "--debug" ] ; then
+MAKELINK=
+if [ "$1" = "--link" ] ; then
 	shift
-	DEBUG=1
+	MAKELINK=1
 fi
 
 THINNER=
@@ -226,6 +235,13 @@ if [ "$1" = "--thinner" ] ; then
 	THINNER=$1
 	shift
 fi
+
+DEBUG=
+if [ "$1" = "--debug" ] ; then
+	shift
+	DEBUG=1
+fi
+
 
 case $COMMAND in
 	update)
@@ -263,7 +279,7 @@ case $COMMAND in
 		echo "Run with $0 command [options] args"
 
 		echo
-		echo "Update:"
+		echo "Copy/Update:"
 		echo "	$ etertimemachine update /path/from /path/to"
 
 		echo
@@ -271,9 +287,16 @@ case $COMMAND in
 		echo "	$ etertimemachine rotate /path/to"
 
 		echo
+		echo "Delete:"
+		echo "	$ etertimemachine delete --method date --thinner /path/to"
+
+		echo
 		echo "Options:"
 		echo "	--method date|datetime|number   name convention for rotate dirs (date by default)"
 		echo "	--force                         sync target ever if we do not rotate this time"
+		echo "	--thinner log2                  method for deletion"
+		#echo "	--link                          create hard links instead copying to the timemachine dir"
+		echo "	--debug"
 	;;
 	*)
 		echo "$DESCR" >&2
